spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

logging:
  config: classpath:logback-crawler.xml

mybatis:
  mapperLocations: classpath:sqlmapper/*.xml

flyway:
  baseline-on-migrate: true
  baseline-version: 1
  locations:
    classpath:db/migrations
  sql-migration-prefix: V
  sql-migration-suffix: .sql
  encoding: UTF-8